version: '3.9'

services:
  server:
    build: .
    volumes:
      - ./:/app 
    ports:
      - 8080:4000
    env_file:
      - .env 
    links:
      - database
    environment:
      - DB_HOST=database
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=postgres
    command: ['npm', 'start'] 
  database:
    image: postgres:9.6-alpine 
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  database-data: {}
